excerpt_separator: "<!--more-->"
markdown: redcarpet
pygments: true
permalink: "/journal/:year/:month/:day/:title"
source: source

name: mentalized.net
description: The virtual home of Jakob Skjerning
url: http://mentalized.net

ftp_host: "linux41.unoeuro.com"
ftp_dir: "mentalized.net"
ftp_passive: false
