excerpt_separator: "<!--more-->"
markdown: redcarpet
highligher: pygments
permalink: "/journal/:year/:month/:day/:title"
source: source

name: mentalized.net
description: The virtual home of Jakob Skjerning
url: http://mentalized.net

ftp_host: "linux78.unoeuro.com"
ftp_dir: "public_html"
ftp_passive: true

category_archive:
  path: "journal"
monthly_archive:
  path: "journal"

sass:
  sass_dir: stylesheets

defaults:
  -
    scope: # All blog posts
      path: ""
      type: "posts"
    values:
      layout: "post"
